### PR TITLE
Fetch from GitHub

### PR DESCRIPTION
**Pull request by laambrosino**
Addresses issue #218. If there's anything to be fixed between today and tomorrow I can definitely do it, but after that I may not be able to look at it for a long time.

### CODE REVIEW

**Comment by arscan** [comment]
💯 This is amazing! @brianandersonmitre would have killed for this functionality a few months ago.

I see there is a commit regarding rate limiting.  What do we need to know about rate limiting?  At some point during the course of some time period (day, week, month), could we run out of requests?  If so, what is the behavior (graceful, crash?)

My main recommendation is to figure out how you can refactor the code that changes the highlight colors.  In react, you really shouldn't access the DOM through `document.getElementById`.  Instead, do `setState` to save what should be highlighted (if you don't already), and then use that state variable to determine which list element should have a `selected` class.

My second recommendation would be to make the folders more visually obvious, maybe by grouping them all on top and adding a `/` after them.  Very cool how you made that work though, I wasn't expecting that!

If you can figure those out by tomorrow, great, if not, I'm good with merging this in and deploying  as-is because it is immediately useful and appears to be stable (assuming the rate-limiting stuff is ok).  We can always let people use this now and clean it up in the future!

Great job!

**Comment by laambrosino** [comment]
Thanks for the review so quickly!

First for rate limiting: As is, each link has a limit of 60 requests per hour. They're currently "unauthenticated requests", so if we could authenticate them it would be 5000 requests per hour (https://developer.github.com/v3/#rate-limiting). As of now nothing is getting fetched initially (which is what I fixed in one of the commits), but anytime one of the branches or folder is clicked it will re-fetch the data. Me and Dylan talked about trying to do some local caching to limit the amount of requests we are making further, so I think that's the first thing I'll be looking to work on today. When the requests run out, I believe it is throwing some errors in the console and just not showing anything under the GitHub Modules tab.

As for the highlighting buttons, this was one of the things I played around with a lot and tried using setState but it just wasn't working for me (even when I tried to do it just like it is for `this.state.selectedOption`), so I ended up doing it like it is now in order to have it working. I agree it isn't ideal and if I have time will definitely keep trying to fix it.

Making the folders more obvious should be pretty easy and would look better/clearer, so I'll work to fix that today as well.

Thanks again! I'll make sure whatever I have by the end of the day is still functional.

**Comment by arscan** [comment]
Gotcha, seems like local caching (content + [etag](https://developer.github.com/v3/#conditional-requests) would help.  That would potentially lay the foundation for saving modules locally between visits, depending how you implement it.  But that 60 requests per hour per IP address doesn't sound too bad.

**Comment by laambrosino** [comment]
Hi again, I tried to work on those issues today but I think I'd just need more time to get them functional. I thought I was getting somewhere on the highlighting buttons but setState wasn't working correctly for reasons unknown to @dehall and myself. As far as the caching goes, I tried some things but nothing was working how I'd like it. Like you said, 60 requests per hour shouldn't be too bad for now. The folders are now on top of the list for each branch and have a / after them to differentiate, and that all seems to be working well. I didn't include anything I started but didn't finish to keep it functional and wrapped up nicely - the changes I started were messy anyway. Thanks for all of your help, I've enjoyed working on the Module Builder!!

**Comment by arscan** [comment]
No problem, this is great as-is.  I think it is a good idea for us to see how big a problem the rate limiting thing is in practice anyhow before putting a lot of work into it.  And I'll take a look at the highlighting portion at some point.  It isn't a big deal.

**Comment by arscan** [comment]
Deployed!

**Pull request merged**
