### PR TITLE
fix attribute not being always a number

### LINKED ISSUE #128: Attribute field doesn't take value from keyboard
I created a Guard state, attempting to only allow people with a certain attribute value.

I wanted the condition to be `'post_procedure' == true`

Here is the state:
```
"Only Post Ops": {
      "type": "Guard",
      "allow": {
        "condition_type": "Attribute",
        "attribute": "post_procedure",
        "operator": "==",
        "value": "Vicodin"
      },
      "direct_transition": "Under 21"
    }
```

If I try to change the value `"Vicodin"` in the editor, the change never gets accept.

### PR DESCRIPTION
**Pull request by schreiaj**
Resolves #128

### CODE REVIEW

**Comment by arscan** [comment]
Is it ok to have quotes around ```true``` in the generated json?

**Comment by jawalonoski** [comment]
The GMF actually handles booleans here as well, so if you convert it into a JSON boolean it would work (from `org.mitre.synthea.helpers.Utilities.java`:
```java
    if (lhs instanceof Number && rhs instanceof Number) {
      return compare(((Number) lhs).doubleValue(), ((Number) rhs).doubleValue(), operator);
    } else if (lhs instanceof Boolean && rhs instanceof Boolean) {
      return compare((Boolean) lhs, (Boolean) rhs, operator);
    } else if (lhs instanceof String && rhs instanceof String) {
      return compare((String) lhs, (String) rhs, operator);
```

**Comment by arscan** [comment]
What if lhs is an instance of Boolean and rhs is an instance of String, as what I think will be the case here?  Seems like the module builder might need to do some ugly checking on string values that are true or false and automagically turning them into boolean in the state tree @schreiaj.  Is that how we are handling numbers already?

**Comment by jawalonoski** [comment]
No, you're reading it wrong, that can't happen. The string is the name of the attribute. The value can be string, number, or boolean. The name of the attribute is resolved to a value before the code I showed is executed.

**Comment by schreiaj** [comment]
I'll get this to convert to boolean if it's a boolean. According to the wiki, however, the value of the attribute can only be a number or a string, might be worth updating.

**Comment by schreiaj** [comment]
@jawalonoski sorry, been busy doing stuff on other project, this adds in automatically casting to boolean if it's a boolean value.

**Pull request merged**
