### PR TITLE
Added option to calculate remaining % in distributed transition

### PR DESCRIPTION
**Pull request by laambrosino**
Addresses issue #217

### CODE REVIEW

**Comment by arscan** [comment]
Looks good!

Question: Would it make sense to have the `Change to remainder` button only show up if they do not add up to 100%?  It doesn't do anything if the numbers are good already.

**Comment by laambrosino** [comment]
That makes sense, I changed it so the button only appears when the weights don't equal 100% and I checked that it works

**Comment by arscan** [comment]
When you click on `Change to Remainder` button on named distributions, it changes it back to an 'unnamed' distribution.  I suppose that should just leave it as a named distribution, but with the default weight now set to the remainder when clicked.  @dehall mentioned that the default value could be blank in #217.  It doesn't appear that the interface really supports that very well, but maybe I misread his description.

screen shot 2018-08-08 at 9 33 32 am

**Comment by laambrosino** [comment]
That issue should be fixed now. Dylan mentioned that to me about default values being optional as well and having to disable the remainder button if one isn't provided, but I noticed that its not currently supported in the module builder to not provide a default value, so it should work fine as is. I also looked on the wiki for Synthea and it didn't say anywhere that the default is optional.

**Pull request merged**
