### PR TITLE
Add ValueSet based code selection to Module Builder UI

### PR DESCRIPTION
**Pull request by kaicode**
Following on from [709](/synthetichealth/synthea/pull/709) in the Synthea project where John Grimes added support for code selection using FHIR ValueSets..

This pull request: 
- Adds the ability to specify a ValueSet URI within the Module Builder user interface.

Work was completed by [Elimu](elimu.io) on behalf of SNOMED International.

[Another pull request](https://github.com/synthetichealth/synthea/pull/758) has been raised against the Synthea project to enhance the ValueSets feature there.

### CODE REVIEW

**Comment by jawalonoski** [comment]
Thank you for the pull request and the code contribution, and apologies for the delay in reviewing this.

**Comment by jawalonoski** [comment]
Couple of requests... (the ValueSet URL's are completely incorrect in the examples below)

## Do Not Display Empty ValueSets
I would appreciate it if you could make the ValueSets not display if they are not set... For example,

- Preferred:
  - image
  - image

- Not Preferred:
  - image

## Do Not Export Empty ValueSets
Similarly, empty value sets should not be exported if possible... For example,

- Preferred:
```json
    "Dialysis_Encounter": {
      "type": "Encounter",
      "encounter_class": "ambulatory",
      "codes": [
        {
          "system": "SNOMED-CT",
          "code": 185347001,
          "display": "Encounter for problem (procedure)",
          "value_set": "http://valueset.org/snomed/encounters"
        }
      ]
```
 OR
```json
    "Dialysis_Encounter": {
      "type": "Encounter",
      "encounter_class": "ambulatory",
      "codes": [
        {
          "system": "SNOMED-CT",
          "code": 185347001,
          "display": "Encounter for problem (procedure)"
        }
      ]
```
- Not Preferred:
```json
    "Dialysis": {
      "type": "Procedure",
      "codes": [
        {
          "system": "SNOMED-CT",
          "code": "265764009",
          "display": "Renal dialysis (procedure)",
          "value_set": ""
        }
```

**Comment by jawalonoski** [comment]
## ValueSets are Optional

image

It would be nice if the Value Set field declared that it was optional, something like "Value Set (Optional):" or "Value Set: optional" (rather than the red "Enter value")

**Comment by kaicode** [comment]
Hi @jawalonoski. Thanks for the review. The changes you requested have been made.

- ValueSets are Optional
  - Screenshot 2020-08-18 at 13 21 49
  - The red text seems to be the default styling for empty fields within the application.

- Do Not Display Empty ValueSets
  - Screenshot 2020-08-18 at 13 29 35
  - Screenshot 2020-08-18 at 13 26 43
- Do Not Export Empty ValueSets
  - Screenshot 2020-08-18 at 13 43 20

**Comment by jawalonoski** [comment]
This change has been deployed.

**Comment by kaicode** [comment]
Thank you @jawalonoski and @amol-wani-elimu.

**Pull request merged**
